- name: variable preference
  hosts: local
  connection: local
  vars:
    greetings: hello from playbook
  vars_files:
    - greetings-file.yaml
  vars_prompt:
  - name: greetings
    prompt: say greetings
    private: false
  tasks:
  - name: greeting 
    ansible.builtin.debug:
      msg: {{ greetings }}