- name: test-playbook
  hosts: localhost
  become: yes
  tasks:
    - name: test
      ansible.biultin.debug:
        msg: "{{ p_name }}"

#    - name: install nginx
#      ansible.builtin.dnf:
#        name: nginx
#        state: installed
#
#    - name: start nginx
#      ansible.builtin.systemd:
#        name: nginx
#        state: started
#        enabled: yes

