- name: test-playbook
  hosts: all
  become: yes
  tasks:
    - name: install nginx
      ansible.builtin.dnf:
        name: nginx
        state: installed

    - name: start nginx
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes